# Generated by Django 4.2.7 on 2023-11-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='uploaded_at',
        ),
    ]
